config/routes.rb
Rails.application.routes.draw do
  resources :cars


  devise_for :users
  root to: "home#index"
	devise_scope :user do  
  get 'login', to: 'devise/sessions#new'
  delete 'logout', to: 'devise/sessions#destroy' #essential to now create stuff.
	post "/user" => "registrations#create" #essential to now create stuff.
	end
  get "/" => "home#index", as: "home"
  

  get 'edit' => 'cars#edit'
  post  'edit'   => 'cars#update'

  # get 'edit' => "cars#edit"
  # post 'edit' => "cars#update"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  

  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

#   def initialize(user)
#     # Define abilities for the passed in user here. For example:
#     # can :manage, Car, user_id: user.id
#       user ||= User.new # guest user (not logged in)
#       if user.admin?
#     #     
#         if user
#     can :manage, Car, user_id: user.id
# end
    #   else
    #     can :read, :all
    #   end
    # #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	belongs_to :user, optional: true

	has_attached_file :avatar, :styles =>{ :medium => "1000x1000>", :thumb => "400x400>" },:default_url => "car.png"

	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord

has_many :cars
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

before_action :authenticate_user!


def index
	@cars = Car.order('town ASC')
end

def show
	@car = Car.find(params[:id])
end
 
def new
	@car = Car.new
end

def create
	@car = current_user.cars.create(car_params)
	if @car.valid?
		flash[:notice] = "Your location has been saved."
		redirect_to "/cars/"
	else
		flash[:notice] = "Your profile was NOT created."
		render 'new'
	end
end

def edit
	@car = Car.find(params[:id])

end

	

def update
	@car = Car.find(params[:id])
	@car.owner = params[:car][:owner]
	@car.email = params[:car][:email]
    @car.town = params[:car][:town]
    @car.brand = params[:car][:brand]
    @car.model = params[:car][:model]
    @car.year = params[:car][:year]
    @car.mileage = params[:car][:mileage]
    @car.available_on = params[:car][:available_on]
    @car.available_until = params[:car][:available_until]
    @car.description = params[:car][:description]
    @car.rent = params[:car][:rent]
	if @car.save
		redirect_to "/cars/"
	else
		redirect_to "/"
	end
end

def destroy
    Car.find(params[:id]).destroy
    	redirect_to "/cars/"
  end


private
    
    def car_params
      params.require(:car).permit(:owner, :email, :town, :user_id, :brand, :model, :available_until, :rent, :year, :mileage, :available_on, :description, :avatar)
    
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cars/index.html.erb
<body id="course_wrap">

<link href='https://fonts.googleapis.com/css?family=Averia Serif Libre' rel='stylesheet'>

<div id="course_wrap">
<p id="font_for_cars_in">CARS AVAILABLE FOR RENT</p>
<p id="btn_to_add"><%= link_to("Add A Vehicle", new_car_path)%></p>


<div id="padding">
<% @cars.each do |car| %>
	<h1><%= car.town%></h1>
	<div id="move_car">
		<%= image_tag car.avatar(:thumb) %><br>

		<i><%= car.year %> <%= car.brand %> <%= car.model%></i><br>
	</div>
	<div id="font">
		<%= number_with_delimiter(car.mileage, :delimiter => ',')%> Miles<br>
		<div id="date1">Available For Rent: <%= car.available_on.try(:strftime, '%B %d, %Y')%><br>
		Expected Return Date: <%= car.available_until.try(:strftime, '%B %d, %Y')%><br>
		</div>
		Rent: $<%= car.rent%><br>
		

        
		<p id="btn"><%= link_to("Select Vehicle", car_path(car)) %></p>

     <%if current_user.id == car.user_id%>
            <%= link_to("Delete", car_path(car), method: :delete, :id => "delete_button_float") %></p> 
            <%= link_to("Edit", edit_car_path(car), :id => "edit_button_float") %></p>
        <%end%><br><br><br><br><br><br><br>
		
	</div>
</div>

</body>

<style>

#index_image {
    border-radius: 5px;
    cursor: pointer;
    transition: 0.3s;
}

#index_image:hover {opacity: 0.7;}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
}

/* Add Animation */
.modal-content, #caption {    
    -webkit-animation-name: zoom;
    -webkit-animation-duration: 0.6s;
    animation-name: zoom;
    animation-duration: 0.6s;
}

@-webkit-keyframes zoom {
    from {-webkit-transform:scale(0)} 
    to {-webkit-transform:scale(1)}
}

@keyframes zoom {
    from {transform:scale(0)} 
    to {transform:scale(1)}
}

/* The Close Button */
.close {
    position: absolute;
    top: 15px;
    right: 35px;
    color: #f1f1f1;
    font-size: 40px;
    font-weight: bold;
    transition: 0.3s;
}

.close:hover,
.close:focus {
    color: #bbb;
    text-decoration: none;
    cursor: pointer;
}

.modal-content {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
}


/* 100% Image Width on Smaller Screens */
</style>
</head>
<body>


<!-- The Modal -->
<div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>



<script>


// Get the modal
var modal = document.getElementById('myModal');

// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById('index_image');
var modalImg = document.getElementById("img01");
img.onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() { 
    modal.style.display = "none";
}
</script>

<% end %>

app/views/cars/show.html.erb
<div id="course_wrap">

<body>
<link href='https://fonts.googleapis.com/css?family=Averia Serif Libre' rel='stylesheet'>
<div id="padding">
<div id="text_in_show">
	<p id="car_in_town"><%= @car.year %> <%= @car.brand %> <%= @car.model%> in <%= @car.town%></p><br>
</div>
	<div id="size_image"><%= image_tag @car.avatar(:medium)%></div><br>

	<div id="font_in_show">
		<%= number_with_delimiter(@car.mileage, :delimiter => ',')%> Miles<br><br>
		<div id="date">Available For Rent: <%= @car.available_on.try(:strftime, '%B %d, %Y')%><br>
		Expected Return Date: <%= @car.available_until.try(:strftime, '%B %d, %Y')%><br><br></div>
		Rent: $<%= @car.rent%><br><br><br><br>
	</div>
	
  <div id="description"><%= @car.description%></div><br><br><br>
	</div>
</div>


<div id="center">
  <h3>Interested? Send a message to owner, <%= @car.owner%></h3>
  <%= mail_to @car.email, "Email Owner"%><br><br><br><br><br>
  </div>

</body>

app/views/home/index.html.erb
	<p id="about_home">Is another car sitting idly in your garage? Don't let it take up space with nothing to do! Rent your car out while your son or daughter is in college (studying hopefully)! Short term rentals as short as a semester. Set your prices. Make some good money off them for once. <b>Safe. Secure. Easy!</b><br><br>
	Need a car? Thinking of earning some extra cash as a driver but don't have a car? Check out the avaiable cars for rent across Northern New Jersey!</p>

	<%= image_tag("student.jpg", :height => "400", :width => "auto", :id => "student_car") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarsDuringCollege</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	

<link href='https://fonts.googleapis.com/css?family=Averia Serif Libre' rel='stylesheet'>
<div id="course_wrap">

<% if user_signed_in? %>
        <li><%= link_to "Logout", destroy_user_session_path, :id => "logout", :method => :delete %></li>
    <%end%>

	<h1 id="home_title">College Car Rentals</h1>
	<p id="slogan">Now it's THEIR turn to make you money!</p>
	<div id="dad_home"><%= image_tag("dad.png", :height => "200", :width => "auto") %></div><div id="student_home"><%= image_tag("student.png", :height => "175", :width => "auto") %></div>
	<div id="car_home"><%= image_tag("car2.png", :height => "75", :width => "auto") %></div>
	<p id="btn_for_bergen"><%= link_to("Bergen County", "/cars/")%></p>
  <p id="btn_for_home"><%= link_to("Home", "/")%></p>





    <%= yield %>

  </body>
</html>